### ISSUE TITLE
Closed connection not removed from pool 

### ISSUE THREAD

**Issue by matchish** [RemoteMetering/geteventstore-promise#102]
https://github.com/RemoteMetering/geteventstore-promise/blob/2858f4072057205add807faf1a74705645af3855/lib/tcpClient/connectionManager.js#L33
After a connection is closed we still have it in a pool. Should be removed from pool also

**Comment by mmuller99** [comment]
Hi @matchish, on close of connection, the connection will now be attempted to be removed from the pool.
