### ISSUE TITLE
Opening and closing a connection on every write

### ISSUE THREAD

**Issue by ryanworl** [RemoteMetering/geteventstore-promise#24]
When writing events using the TCP connection, this library opens and closes a new underlying `event-store-client` connection each time.

On my machine, this overhead results in speed reduction over using the `event-store-client` library directly and a much larger CPU overhead due to opening and closing so many connections.

For example, when writing one event at a time, I could only write around 4500 events per second with this library and I can write around 50000 events per second using `event-store-client` directly.

**Comment by mmuller99** [comment]
Hi @ryanworl , thanks for raising the concern. We have not implemented any sort of connection pooling as of yet. Marked as enhancement

**Comment by mmuller99** [comment]
Implemented in 1.1.25
