### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by DavidBM** [RemoteMetering/geteventstore-promise#48]
Hi! 

First of all, great job! I find this the best library out there for using eventstore! 

We are migrating our project to typescript. Is there any types definition already created for the library? 

Thanks!

**Comment by mmuller99** [comment]
Hi @DavidBM,

My apologies for only getting back to you now.  Thanks for the vote of confidence!

We will definitely be adding definitions in the near future as soon as we find time, it's on our todo's.

As always, pull requests are welcome.

Thanks

**Comment by mmuller99** [comment]
Added in 3.0

**Comment by DavidBM** [comment]
Thanks! :D
