### ISSUE TITLE
how to connect to cluster eventstore (1st by using tcp and secondly using gossip seeds array) ?

### ISSUE THREAD

**Issue by Pk5037** [RemoteMetering/geteventstore-promise#49]
How we can connect to cluster eventstore using geteventstore-promise

**Comment by arindamdat** [comment]
Your question is not clear. Do you mean how you can achieve one of the following?
1. Connecting to a cluster using "discovery" protocol?
2. Passing an array of Gossip seeds (array of ips) to the connection manager?
It seems the underlying lirary node-eventstore-client provides these features.
@mmuller99 : is there an way we can use a cluster and also use "geteventstore-promise"?

**Comment by mmuller99** [comment]
Hi @Pk5037, @arindamdat,

My apologies for only getting back to you now.

Both gossip seeds and dns discovery have been implemented in 2.0.2.

Please see: [https://github.com/RemoteMetering/geteventstore-promise#config-example](https://github.com/RemoteMetering/geteventstore-promise#config-example)
