### ISSUE TITLE
Is there any way to force ip v4 familly?

### ISSUE THREAD

**Issue by AlexandruSimandi** [RemoteMetering/geteventstore-promise#69]
First of all thanks for making the module.
Back to business.
Previously I used to do it like this when it was using request-promise
`require('request-promise').defaults({family: 4})`
`const eventstore = require 'geteventstore-promise'`
But now it's using axios and from my research there is no workaround.

The reason why I need this is because kubernetes has some shady networking issues on ip v6 and causes random disconnect and usually leaves subscriptions in limbo.

**Comment by mmuller99** [comment]
Hi @AlexandruSimandi , thanks for using the package.

I found a logged issue [https://github.com/axios/axios/issues/444#issuecomment-246413689](https://github.com/axios/axios/issues/444#issuecomment-246413689) with a possible solution, it is a few years old though.  Perhaps using the global defaults option with the httpAgent will suffice?

**Comment by AlexandruSimandi** [comment]
@mmuller99 worked brilliantly thanks
